### ISSUE TITLE
멤버 - 멤버 수정

### ISSUE THREAD

**Issue by highsilverr** [nhnacademy-be8-Hexa/Hexa-Shoppingmall-Service#8]
`###` **사용자 입장** 

마이페이지의 멤버 수정

해당 페이지의 사용자의 정보를 가져와서 
이름 , 연락처 , 이메일 , 생일등을 수정할 수 있게 할 수 있습니다. 

수정완료와 취소 버튼을 하단부에 배치하고 ,
수정완료를 누르면 정보가 수정됩니다.

취소를 누르면 기존 마이페이지로 돌아옵니다.
 

### **관리자 입장**

특정유저의 멤버를 수정할 수 있는 페이지 입니다.

아이디 , 이름 , 연락처 , 이메일 , 생일 , 가입일 , 마지막 로그인 ,
권한 , 등급 을 수정할 수 있습니다.

아이디를 수정 시에는 회원 가입에 사용한 중복 아이디 체크를 활용하여 아이디를 수정합니다. 

수정완료와 취소 버튼이 있으면 수정완료시 서버로 해당 정보를 보내고, 검증을 통해 반영됩니다. 검증 단계에서 오류가 발생할 시 수정 실패 메세지를 보내고 수정은 무효화 됩니다.

취소 버튼을 누르면 기존에 진행하였던 정보수정은 무효화하고, 이전 멤버 리스트 페이지로 넘어갑니다.

**Comment by iooah** [comment]
관리자 입장

아이디 , 이름 , 연락처 , 이메일 , 생일 , 가입일 , 마지막 로그인 ,
권한 , 등급 에서

  아이디, 가입일, 마지막 로그인을 제외한 나머지 필드들만 수정할 수 있게 했습니다.
