### ISSUE TITLE
멤버 - 멤버 삭제 기능

### ISSUE THREAD

**Issue by highsilverr** [nhnacademy-be8-Hexa/Hexa-Shoppingmall-Service#9]
`###` **사용자 입장** 

마이페이지의 회원 탈퇴

마이페이지의 하단부에 회원 탈퇴 버튼을 만들어 회원 탈퇴를 합니다.

### **관리자 입장**

특정유저의 멤버를 삭제 할수 있습니다.

관리자의 멤버리스트 페이지에서 각 유저마다 유저 삭제 버튼이있습니다.

유저삭제 버튼을 누르면 해당되는 유저의 정보가 삭제 됩니다.

**Comment by iooah** [comment]
관리자 입장
삭제버튼을 누르면 회원 상태가 탈퇴로 변경
